using Godot;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

public partial class day4 : Node
{
    private string _puzzleInput;
    private List<string> _puzzleInputLines = new List<string>();
    private List<string> _puzzleInputVerticalLines = new List<string>();
    private List<string> _puzzleInputDiagonalDownRightLines = new List<string>();
    private List<string> _puzzleInputDiagonalDownLeftLines = new List<string>();

    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        // Create puzzle input lists for horizontal, vertical, and diagonal

        // Horizontal lines
        _puzzleInput = GetPuzzleInput();
        _puzzleInputLines = _puzzleInput.Split("\n").ToList();

        int puzzleInputWidth = _puzzleInputLines[0].Length;
        int puzzleInputHeight = _puzzleInputLines.Count;

        // Vertical lines
        for (int i = 0; i < puzzleInputWidth; i++)
        {
            _puzzleInputVerticalLines.Add(GetVerticalString(i));
        }

        // Diagonal Lines
        // Start at each index along the top 
        for (int i = 0; i < puzzleInputWidth; i++)
        {
            _puzzleInputDiagonalDownRightLines.Add(GetDiagonalDownRightString(0, i));
            _puzzleInputDiagonalDownLeftLines.Add(GetDiagonalDownLeftString(0, i));
        }

        // Start at each index along the side columns (excluding the first as we already got that in the last step)
        for (int i = 1; i < puzzleInputHeight; i++)
        {
            _puzzleInputDiagonalDownRightLines.Add(GetDiagonalDownRightString(i, 0));
            _puzzleInputDiagonalDownLeftLines.Add(GetDiagonalDownLeftString(i, puzzleInputWidth - 1));
        }


        GD.Print("Day 4 Part 1: ");
        ExecutePart1();
        GD.Print("\nDay 4 Part 2: ");
        ExecutePart2();
    }


    public void ExecutePart1()
    {
        int matchCount = 0;
        // Get count for all horizontal matches
        foreach (string line in _puzzleInputLines)
        {
            matchCount += GetXmasCount(line);
            matchCount += GetSamxCount(line);
        }

        // Get count for all vertical matches
        foreach (string line in _puzzleInputVerticalLines)
        {
            matchCount += GetXmasCount(line);
            matchCount += GetSamxCount(line);
        }

        // Get count for all diagonal down right matches
        foreach (string line in _puzzleInputDiagonalDownRightLines)
        {
            matchCount += GetXmasCount(line);
            matchCount += GetSamxCount(line);
        }
        
        // Get count for all diagonal down left matches
        foreach (string line in _puzzleInputDiagonalDownLeftLines)
        {
            matchCount += GetXmasCount(line);
            matchCount += GetSamxCount(line);
        }

        GD.Print(matchCount);
    }

    public void ExecutePart2()
    {
        // Concept for my approach to part #2
        // Using RegEx on the diagonal down-left and down-right lists, search for any occurence of MAS or SAM
        // Store the coordinate [x,y] position of the center 'A' character in the match for both left and right lists
        // A cross-MAS is any place where a center coordinate is shared between both diagonal lists
        // The tricky part is that the coordinates from the down-right and down-left lists need to be converted to global x,y coordinates.

        List<(int, int)> downRightCoordinates = new List<(int, int)>();
        List<(int, int)> downLeftCoordinates = new List<(int, int)>();

        var regPattern = @"(?=MAS)|(?=SAM)";
        Regex rg = new Regex(regPattern);

        for (int i = 0; i < _puzzleInputDiagonalDownRightLines.Count; i++)
        {
            // Find Down Right Matches
            string downRightString = _puzzleInputDiagonalDownRightLines[i];
            MatchCollection matches = rg.Matches(downRightString);
            
            // Iterate through matches and convert from diagonal coordinates to global x,y
            foreach (Match match in matches)
            {
                int centerIndex = match.Index + 1; // We want the index of the center 'A' character.
                // In our right diagonal list, the first 140 lines all start at the top row, then the next 140 descend down the left side column
                int startCol = 0;
                if (i < 140) startCol = i;
                else startCol = 0;
                int colCoord = startCol + centerIndex; // Each character into the string moves one position to the right
                int rowCoord = Math.Clamp(i - 139, 0, Int32.MaxValue) + centerIndex; // First 140 lines start at the top row
                downRightCoordinates.Add((colCoord, rowCoord));
            }
        }
        
        for (int i = 0; i < _puzzleInputDiagonalDownLeftLines.Count; i++)
        {
            // Find Down Left Matches
            string downLeftString = _puzzleInputDiagonalDownLeftLines[i];
            MatchCollection matches = rg.Matches(downLeftString);
            
            // Iterate through matches and convert from diagonal coordinates to global x,y
            foreach (Match match in matches)
            {
                int centerIndex = match.Index + 1; // We want the index of the center 'A' character.
                // In our left diagonal list, the first 140 lines all start at the top row, then the next 140 descend down the right side column
                int startCol = 0;
                if (i < 140) startCol = i;
                else startCol = 139;
                int colCoord = startCol - centerIndex; // Each character into the string moves one position to the left
                int rowCoord = Math.Clamp(i - 139, 0, Int32.MaxValue) + centerIndex; // First 140 lines start at the top row
                downLeftCoordinates.Add((colCoord, rowCoord));
            }
        }
        
        // Count the amount of matching center coordinates
        int centerMatchCount = 0;
        foreach ((int, int) coordinate in downLeftCoordinates)
        {
            if (downRightCoordinates.Contains(coordinate)) centerMatchCount++;
        }
        
        GD.Print(centerMatchCount);

    }

    private int GetXmasCount(string input)
    {
        var regexPattern = @"XMAS";
        Regex rg = new Regex(regexPattern);
        MatchCollection regMatches = rg.Matches(input);
        int count = regMatches.Count;
        return count;
    }

    private int GetSamxCount(string input)
    {
        var regexPattern = @"SAMX";
        Regex rg = new Regex(regexPattern);
        MatchCollection regMatches = rg.Matches(input);
        int count = regMatches.Count;
        return count;
    }

    // Returns a string that is a vertical column of the puzzle input at column (index)
    private string GetVerticalString(int index)
    {
        string output = "";
        foreach (string line in _puzzleInputLines)
        {
            output += line[index];
        }

        return output;
    }

    // Returns a string that is a diagonal line of puzzle input that starts at [startColIndex, startRowIndex] and continues down-right until edge of input
    private string GetDiagonalDownRightString(int startRowIndex, int startColIndex)
    {
        string output = "";
        int inputHeight = _puzzleInputLines.Count;
        int inputWidth = _puzzleInputLines[0].Length;

        int row = startRowIndex;
        int col = startColIndex;

        while (row < inputHeight && col < inputWidth)
        {
            string rowString = _puzzleInputLines[row];
            output += rowString[col];
            row++;
            col++;
        }

        return output;
    }

    // Returns a string that is a diagonal line of puzzle input that starts at [startColIndex, startRowIndex] and continues down-left until edge of input
    private string GetDiagonalDownLeftString(int startRowIndex, int startColIndex)
    {
        string output = "";
        int inputHeight = _puzzleInputLines.Count;

        int row = startRowIndex;
        int col = startColIndex;

        while (row < inputHeight && col >= 0)
        {
            string rowString = _puzzleInputLines[row];
            output += rowString[col];
            row++;
            col--;
        }

        return output;
    }

    private static string GetPuzzleInput()
    {
        return
            @"MXMXMAMXAXMSMMMSSSXSSSMXXMSSXSMSASXSMXSAMXSMMMSMSMMSSXMSMSMSMMMSSMAAXSAMXSMSSMASAMMMSAMXSSSSSSSSXSAXMMMAXMMSSXMASXXSAXSXXAMXSSMSXMSAMXMAMAMX
SMMAMXMSAMXAAAAAXMAMXAMAASAMSXXXAXAXAASAMAAAAAAXMAAAMAMXAAMAAAAAAMMXMSXMASAAAMXMAMAMSAMXXAMAAAAAXMAMSASMXSAASASAXMAMXMASMASASAMXASXMSMSMSSSM
AMSMSMXXAAXXSMSSMMAMSXMASMASAMXMMMMMMMXAMASMMSSSSMMSSMMMSMSSSMMSSMXAASXMASMSMMASMMXXXMASMAMSMMMMMMXMSASMAMMSSXMSXMXMAMAMSAMXSAMSXMAMAAAAAAAA
MMMAAAMMSSSMXAXMAXAMXMXSAMXMAMSAAAAASMSSMMAAAAAAAMAMAMAAAAXMAMAMXMSMXSASMXXMASASAMXMASASMSMMAXXXMASMMMMMAASAXXXXMSAMASAXMXSXMAXMASXXASMSMMMS
XMMSMMAXAAAASAMASMMSMSMMMSSSXMAMXMMMSAAXAMXMMMSMMMASAMMMSSMXXMXXAXAMXSAMXXASAMXSAMAMMMMSAMASMMSMXMAXAAXMASMMMMSSMSASASMSMAMMAMMMAAMSMMAMXXXX
MXMXMASMMSMMMAMAMAAXAAAMAAMXMSSSSXSAXMASXMAXXAXXXXXMMSSXMAXAASMSMSASAMAMAMXMMMXSXSAMMMAMAMAMMAAASMMSSSSMXMASMMAAXSAMXSAXMAMAAXSAMXAAXMAMXXMS
AAMXMMXAXMAMSAMXSMMMSMSMMMSAMMXAAASAMXMMASXSMMSXASAMXAMASAMXMMAAXXMMXSAMXSAAASMMMSMMAMASMMASMSSSXAAAAAXMASAMAMSSMMXMXMXMMSSSSSMXSMSMMSAMMXMX
SXSAMSSSMSXMSASAXAXXAXXXMASASXMSMXMAXXAXXMMSAASMMMSSMSXMMXMMMMSMSMSSMSASXSMSMSASMSMMMSAMAXAAXAMMXMMMMMMSAMXSXMMAXSAMXMASXMAXXXXAXXAMXSSXSAMA
MAMMSAAMAXSAMXMASMXSAMXMMASMMMAMXSMSMSMMSAASMMMAXMAMXAMSASMSAAMAAMAAXMAMAMAMXSAMASAAXMXSAMMMMMSSSXXMASAXSSMMAMSAMXAMXSAMAMXMMSMSSSMMXMAMSASM
XAMXMMSMSMXMASXAXXAMASXAXAXASMSMSAAAAXMASMMMXSSSMMASXMASAMASMSMXMMSSMMXMAMMXMMMMAMXMSAMXXSAXMAAAXMSXMAASASAXAMMASMMMMMMXXSAAAAAAMXSAAXSMSXMM
XMXXXXAAXXXMAMMMSMXSAMASMMSASAMXSMXMXMSMMASXAMAMXSASMXAMAMXMXAXXMAMAXAXSSMSXAAAMXSXMMMMMASASAMMSMMMAXXMMASXMSXSAMAAXMASAAAMSSMSMMAMMSMXASAMX
XSASMSMSMSMMAMAMXAAMASAMSXAXMAMAMXMAXXXMMAMMMSAMXMASMMXMMSSXSSSXMAMAMMMMAAXMMXXSAMASAMXSASAMMAXMXSAMMSXMAMAXXAMXSSMMSAMMSMXXMXMXMASAMAMXMAXX
XAAMAAAAAXXMASMSMMMSAMASMMSXSAMAMAASXMAMMAMAXSMSXMXMMMMSAMXAXAMXSSXSASASMMMMSSMMASAMSXXMAMMMXSMSASASAXAMXSMMMXMAMASAMXSXXXMMAAMAXAMMXXAMSSMS
SMSMSSSMSMSMASMAAAAMASXMMAMASASXXXMXASXMSAMSAMASMMMAAAXMAMMAXXMAXXAMXMASXAXMAAXSAMXXMSXMXMAMAMAMASXMXSXSMMXAAAMMSAMXSXSAMAMAMSSXMMSSSMSXMMAA
XXXAAAMXMAAMSMMXMMXSMMAAMXSASMMMSSSSXMMXMAMMAMXXAASMMXSSXMAMAXMXSMMMAMXMMASMSSMXXMXAMXSAMSMSSMSMMMMMAMMMAXSMSXSAMMMXSMSAMAXSMAXAXSAAAAXAAMSM
SSMMMMMAMMMMXAASAMXXXSMMMMMMSXXXAAXMAXMAXSMXSMXMMMSAAAMXMMSSMMXMAXXMAXMAMXAXMAMMSMMASAMXASXAMAMMAAAXAAAMSMSXMAXMXMSXMASAMXMXMASMMMMSMMMSXMMX
SAMMSMSMSSSMMSMXMAAMXMSMAAMAMXMMMSMMMMSSSXSAXMMMAAMMMMXAXAAAAXMSAMMSASAXSSMXSMSAAXAMMMMXSXMXXAAXXXMSMSMMAAXAMMMSAMXAMXMXMXAXMASXSXXXAMAXAXMM
SMMXAAAAXAASAMXASMSMMAASMSSSXAASAAMAAAXXAAMXMAASMMSAMSSMMMSSMMMMAMAMAXMAAAMMSAMMMSSXAMSMMSSXSSSSMMXAMXXXMXMXAAASASXXMXSAMXSAMXSAMXXSAMASMMSS
MXSSMMMSMSMMXSSMSAAXMSMSXAAXMSSMMSSSSSMMMMMAMSMSAASAMXAXMXAAAAXSAMMSSMXMSXSAMMMMMSASXMAAMAMMAAAAASXMSXMASXMSSMMSAMXAAAXASAMASAMAMMMSAMMXMAAA
XAXAAASXMXAMSAMXMMMMMAAXMMMMAMAXAMMAAAMMXAXAXXAMMMSAMXMMMMMSMMMSASAAAMXAMXMMMXAMXSASMSXSMASAMMMMMMAXSAMMMAAXXSAMXMXAMXXXMASAMMSSMMAXSMAXMMSS
MASMMMSAMXAMMMSAMXXAMMMMXSAMXSAMSSMMSMMASMSSSMSMXXXMASXAMAAXASASXMMXSMASXSSSMSMMAMAMXSAAXXSMXXSSSSSMMSSMSMMMSMXXAXSSSMSSSMMMSXAAXMMSMMMMXMAX
SASAMXSAMSSMAASAMSASXSMXAMXMXMMAAXMMMMMXMAAXMAXASXMMXXSSSMMSAMAMMASAXXAAASAAMASMMMMMAMAMAXSXSXSAMAMAMAXMASASAMMSSMAASMAAASXSSMXSXXXAXAAMXMMM
MASXMASAMAMSMMSXMXAMASAMMMSMMMMMMMXAAAMAMMMMMSMAMAASXMAXAAAMXMAMMAMMSMXMXMSMMASXXAXMASASMMMAMSMAMXMAMSSSXXXMAXMAAMMMMMMSMMSAMXMMXMSXXSSXASAM
MAMAMMSSMAMSMMXMMMSMAMMXMASAMXAASXSMSSSMXMXMMAMASMMMAAMSMMMMASMSMXSMXMAMSMXSMXSXSXMSXSAMAAMXMASXMXSXMXAMAMSSXMMSMMXXAXXAXMMXMAAMAXASMMMMAXAS
MSXSMXMXSSMSAMSAXSAMXMXXMASAMSSXSAXAAMAXXAMXXXSXSAMXXSMAAMXSASMAMSXXAXAMXAAMMMMXXAMSAMXSSMSMXAXMAMAMXMAMXMMAXXAXMSSMSMSMSMMMSMSSMMASXAAAMSMM
XMAMXSMAMXASAMSMMSASMXSXMASMMMMAMMMMMSXMASXXSASXMASMMMXSSMMAASXSMSASMSSMAMMSAASMMMMSAMXAMAMMMSSSMSMMXSMMXMXAMMSMAAAAAAAMAMAXAMMAAMSMXMSMMAAA
XMAXAXMASMMMSMSSXSAMXXMAXAMMAXMXAXMSMAMAXMAAMAMAMAAAAAAMAMAMXSAMAMAMMAXXAMAXXMXAAXASAMXMXMXAMMAXASAMXSAXAMAXMXAMMMSSMSMXAMMMAXSSMMAAAXAAMSSM
XMXMSMSMSAMAMXMXMSASMSSMMSSSMSMSMMMAXMASMMMMMMSAMSSSMSXXAXMXAMAMXMAXMAXSSSXSSSMXSMXSAMMXAMXSMMAMXMAXASASASMSSXXSAAXAMXXMSMMSMMXMMMMXMSSSMAAA
XAMSAAAXSXMASAMAAMAMAMXXAAMAAAXAASXXSMMXAAXXMAMXXXMAXAMSMSMMASAMXMSSMMMAAMASAAMAMXMXAMAMASMAXMASXXXMXSAAAXMAXASXMMSMMASXMAAAASXMMMSAAXAMXMMM
MSMXMMMXSMSASASAXMAMAMMMMMSMSMSSSMMSMAMSXMXAMXXSAMXXXMXAAAXAMMXSXAAAAXMMMMSMSMMAMASXMMMXAMMMMMSMMSMMMMMMMMMSSMMSAMMAMASASAMSSMASAAAMXMMMMXXX
AMAMSASMXAMXXAMASXASASASMXAXAAXXAAMMMAMXAMXSSSMMASXMMXSMSMMMASAMMMSSMXXAXXXAMXMASMMAASXSMMSXMXAAMAAAXSAMXAAXXXAXMMXAMAMMMMAMXXAMMSMMAAAXXXMS
SMMASASMMMMSMAMAMMMSXMXAXMAXMSMSSMMSSSSSSMAXAAASAMAAMXXAAAMMMMASAAMAMMSMSMMMMXSAXXMXMMXAAAMASMSSMSSMSMMSSMSASMMSASMMMXMASXMASMSAAMASXSXMASXS
XAXMMXMASAAAAAMMSMAMMMMMMSSMXAAXAAXMAMAAXMMMXMMMASXSMMMMMXSAXSSMMSSSMAMMAAASAXMASXMSASXSMMMAMXAXXMAMXXAXXXMAAMAMMSAXAXMASXAMAMXMXSAAAMASXMAS
SMMXXAMASXSSSMXAAMMSAXAXMAAXSXMSMMMMAMMMMAAAASASAMAAXAAXAAXMXXMSXXAXMASMSSMSXSMAMAASAMXMAMMSSSMSXSAXSMMSXXMMMAAXXSXMSMSMSAXSXSMSAMMSASMSAMAS
XMAMMSMASMMAXAMSSSXSXSXMMSSMMMXSAMASXSAMSSXSASASMMSMMSSMMMSXMASMXXMSMMSAMMAMXMMSXMMMAMAMAMXAAAAAASMMMAMMMMMMXSMSAMXMAAAAMAMAAMASMSAXXSXSAMAS
MMASAXMXSAMAMMXMAMAMASMXAXAAXMAMAAASXSAXXAAMAMXMAAXAAAXMAMXAXSAMMSXAMSMMMMSAMXAXAXXXXSMSSSMMSMXMXMMXXAMAAMMSMAMSASAMMMMMMAAXXMAMXMASAMASMMAS
ASASMXXAMXMAMXXMXMSMAMAMXSXMMMXSMMMXMSMMSMXMAMAMMSSMMSMSSSSMMXMXAMMMXXAXAAAAMMASMMSMMAXXMAXXAMSMMAAASMSSXSAAXSAXAMXXMXSASMSSXMXXAMXMAMAMAMAS
MMAXXXMMSMSMSMMXXXAMAXMAMMAXAAXAXXXAAMAAXXSMMXXXAMMAMAASXAAMXMXMMSAXMSSMMSSMMMAAAXAASMMMSMMSASMASMMMSAAAAMMSMMXMSMSMSASASAAAXXSSMSSSXMASXMAM
XMASMMSXAXAMAAAMMMMSASMXAXAMXSAMXMSASXMMSMSAMASMMSXAMMSSMXMMXMASASMSXAAAXMAMXMXSAMSXMAAAAAAMXMMMMXXXMMMMMMXMAMXSAAAAMAMAMMMSMXAAAXXAMSXMXMAS
XMMSAAAAMSMSSMMAAAXMXSASMSAMXAMSAAMAXAXXAAXAMAMAAXXMSXXMAXSAXSAMXSAMXXSMMXAMXMAXAMMMSSMSSSXMASAMMXAMXASMMSASMMXAMMMSMAMXMMAAMASMMMSSMSAMASAS
XMAMMMMSXMMAMASXMSXMXMAMAAXMASAXAXSAXAMSXSMMMSMSMMASAXMMSMXAMMSSMMMMMXMASMASXMASAMXAAXMAXMAMAMAXMMMMSMSMASXXAMXXXAXAMXSAXMXMSAMXSAAAXSAMXXMS
AMASAAXXAMAXMAMAAXMMSMSMMMSXXMXMSMMMXAAXXXASMMAMXAXSASMAMAMXMAXXASAAXAXAMSXMXMASAMMMSSMSMSXMSSSMMSAAAASMMMMXAMMMSAMXMMMMSMSMMASAMMSMMMAMXAXS
MSXSMSXSAMMMMSSMMMAAAMAXXXMMXMXAAAAMSSSMMSAMAMAMXSXXAMMASAMMMXSAMSSXMAXSMMXSXMASMMMAMMAXMMXXXAAAASMSMXSAXAMXXSAAXMSXSAXXAAAXSAMXSXMASXSMSMMX
MMAMXMASXMXAAAAAASMMXSMMXXSAAXAMSXMMAAAXAMMMAMAMMMAMMMXAXXXAMAXXXXAMMSMXAMMMAXAMXMMXSMAMASMMMSMMMSMXXSMXMMSAASMSMAAAXMXSMMMMXXMASAXXMAAMAMSM
MMAMMMAMMXSMSSMMMXXAASXSAASMSXMMMXMMMMMMSSMSMSXSAMXXAAMXSSXSMSSMSMAMAMASMMSSMMXMAMSAMMXXAMAAXMSAMXMMMSMASAMMMMAXAMMMMXMXAAMAMXMMSAMSMSMMAAMA
XMASAMAMMMMMMMMMMMMMMSAMMXMMMMSAAAMASAXMMAASAAAXAXSMSSSXAMAXAXAMASAMXSMXMAXAXMASMXASXASMMSSSMMXMXXMAAXXAMXMMASXXSXSMSSMSSXSAMXMMMMMSAMXSMSXS
SSMSXSAXXAAXAAAMASAAAMAMMXXMAAMMSMSASXSXMMMMMMSSSMSAXAMMAMMMMMMXAMMSMMMAMSMXMSASXSMAMAXAAAAAASMSMASMSSMMXSASAXMAAMMMAAAAAMXAMXAAAAAMAMAXAMMM
XAMMXSASMSMSMSMSASXMXSMSSMAMMMSAXXMMSAMXMSXSAXMAMAMMMAMSXSMXMASMMSAAAAMAMMXSXMAXAAXMAMXMMXMMMMAAAXXMAAAAAMXMXSMSMSAMSMMMSMSSMMMSSMSMSMSMMMMM
SMMMAXMAMMMAXMAMMSXSASAAASXMAXMXMMMAMAMXMXAMAMMAMAXMSXMMMMMASXSAXMXSSMSSSMAMAMAMXMMXSAASMSSXXSSMMMMMMXMMSMXMAMAAXMXMAMXMAMAMXAAXXAXMMAMAXSAS
AXXMAMAMASMMSMXMXMAAAXMSMMMMMMMXMASMSASAMMSMAMSXSXSMXMXMAAXMXMMMSMAMAAAAAMAMSMMSMASAAMMSAAXXXMAMXSXAMXSXXMAMASMSSSSSMMASMMSSSMXSMMMXMAMMASAS
SMSMSMSMASAXMMMSAMXMMMXXAAAASASASXSXSASMSAMMAMXAXXSXAAASMSSSSXMAMMAMSMASXMASAAAAMAMXSXAMMMSXMSAMASMXSAMAMXAMXSXAAAAMMXAXAAAMXSASAMASMXSMMMAM
XAXAAAAMSSMMXAAXAMXAXXAXSMSMSASASASXMAMXMASXMXXXAMMASMMXAXAMMAMSXSAXXXXAAXSAXMMSMMMAXAMXAXMAXSXMASMMMMSAXSXSXMMMMMMMMMSSMMMSAMXSXMASMAAXXMAM
MAMMMSMSAMAMSMMSAMSSMMMXAMXMMMMMMAMAXASXMXMAMSAMXAAAMXMMSMSMSAMAAXMASXXSMMMMXXXXXMSSMMXXMMMSMMASMXXXAXMAMSAMXXAXAAMMMAMAAMAMASXSMSSXMSMMXMAS
AAXAAMXMAMAMAAAMXXAAAAXXSMXAMXSMSSSMMAMXXMSAMXMMASMXSAMXMAMXSSSMMSXMMAAXMAAMXSMMMXXMASMASAMAAMAMXAMMSMMSSXAMMSXXSMSAMXSSMMASXMASAXMAXMXAXSMX
SMXSSSMSAMSSMSMSMMSSMSXSASAMXAXMAAAAMAXSSMMAMMSMXMXASMXMMAMXMAXXASMSSMMMSSSMASAAMSASXMXAXASXMMASMAMAMXAXAMAMXSAAXASMSAMXMSMSAMAMAMSMMXMMMASX
ASXXAXAMXMXAMXMAAAMXAAMSAMXXMXMMMXMXMMMXAMSSMAAXXMMASMSMMAMAMXMMMSAXAXAMAXAMASASXSMMAXMASMMMXSASMSMASMMMMSMXAMMMMAMXMASXMAASMMMSMXAMMAAXSAMS
SXSMAMMXXMSMMMXMMSAMMMXMMMMMMAASAMXXMXSSMMAMMSMXAXMXMAAMSSSMSAXXXMMMSSXSSSMMMSXMXSASMMSMXXASXSAXAAMXMAXAXAXMSSMXMAMAXAMMSMXMMAAAXSASXXSXMAMX
XAAMAMXSMMMMAMXSAMAXAXAAAAAAMXMMASMAXSMAXMASMAASMXMXMSMMAAAASMMAXAMXMSAXAXAAXMASASXMAMASAMXMMMAMSMSAMXAMSMSXMAMSSSSXSAMXSMSASMSAXSMSAAMASAMM
MXMAXSAMAAAMASXMASMMMSMXSSSSMAXSAMMSMAXAMMAXXMAXAAMXMXXMMSMMXSSSSXSAAXMMMSSMSMMMMMMSMSMMXXSMXMSMMAXXXAMXAXAMSAMXAAAMSAMXSASXMAMMMMASMAMAMASA
MAXXXMAXSXSSMSAMXMAXMAMAAXMAXMMXXMAMSMMMSXSSXSXXSSMMSSMXMAXAXMMAAASMMMXMXMAAAXXMAAAAXMXSMMMSAMXMMMMSXSXSMSMMXSMMSMXMSSMAMAMXSMXAXMAMMXMASXMM
SSSMMMSMMAAMMMMMAXMXSASMSMSASMMXSASXSMAXXAMMAMMXMAAXAMMAXMMSMSAMMMMMAMAMASMMMMMSSMSXSMAAAMMAMXXAMXXXAMAAXAAMAMMAXXXXMAMXSXMAMXXMMMMSMSMMXXAA
XAXMSAMAMMMSXMASMSXXMASAMAMASASMSAMMMMSSMAMMAMMAMSMMSSSMSSXMAXAMXXASMSMSASXMAXXAMXAASMSSSMMSSSMAMXAMAMSMMSSMAXMASXMAXMMMMAMXMAAXAMXAMAAMSMMM
MXMAMASMMSAAASMMMSMXMAMXMAMASMAAMAMAMAAAMAMSAMSAXAXXAAAMAMMMSMAAXXXSXAAMASMSSSMMSMMSMAAAMAMMAMXAMMMSAMXAXAXXMMMASAAXXSASMSMMSSXSASMSSSXMAAAM
MSMMXMMAAMMMXMMAAMXAMAMAMXMAXXMMSXMSMMSSMXXMAXSMMASXMSMMASAAAMMMSMSMMMMMMMXMAAXAAASXMMMMMAMMAMSASXAMXXAXMMSXMAMSSMSAMSASAXAXAAAMAMAXMAXSSSSS
AAAXSXMMMMMMSASMMXMSMXMAMAMSSMXMSMAAMXAMMXMMSMMMSAMMMMXSASMMSSMAAXAASXXSASAMXMMSSMMAXXMSMMXSAMXXAMXMSAMXAXMASXMMSMMAAMAMAMSMMSMSSMXMMAMMAMAM
SSSMAXXSXSXASAMXSSMMASXMMAMAAAXAMMSMSXSSXSAAMAAMMSMAXMASAXASXAMSSXXAMXASASAXSAMXMASMMMAMMMMMMSXASXSXAAAXAMXMXSAAXXXMMMXMAMXAXXAAXXXXMASMAMAM
XAAXMXAXAAMMSMSAAAAMAMASXSMSSMMXSXMXAMXXAXMSSMMSAMMSMAMMSMXAMMMMAMXSAMMMXMAMMXMAMMASAMAXSXMAAXXMMAMXSMMXSMSXAXMMMMXMASMSMSXMMMMMSSMMMXXMXMAS
SSSMXMSAMXMXMAMXSMMMAMAMXAAAAXAXSASXXMSMMMXXXAXMMMAAAXAAXXXMSXMSMSMXASXMSMAMXSMSMSASXMASXASMMSMMMSMMXMXAMXAMMSMSASXSMSAASXXAAXMSAXAAMSMXMAXX
XMAXXAMASAAAMMMMXMMMSMSSSMMSMMXXMAMXMAAAXXSXMMSMSMSSSXMMMSXXAAMAAAAMXMAAASASXMAMAMAMAMXAXMMAASMAAMXSASMAXASAMAAMAMMAMXXXSXMSASXMASXMMSAXSAMX
XSAMXMSAMXSASXSSXSAAMAAAXXAXXSXXMXMAAMSXSXMAMSAAAMAMXXMAMMMSSSMMSMSMXSMMMXXSAMXMAMMMSAMXSXSMMMMMMSASASMSAMXAXMSMMMSMMAMMMMAMAMXMXMMMXMAMAAMS
MMXAMAMMMMXXXAMXAXMMMMMMMMXSAMASMMXMSXMAXMXAXXMMMSXMSMSASMAMAXMXMAXMXXMXXMXMXMAMXMAXMAMAMXSAMSMSAMASAXAMXMMSMXAAXAMXMAMAAAMMAMXXMAXSAMMMSMMX
AAASXXXAAMMSMAMMMMSASXMSXSAMAMAAAXSXXAMAMMMMXXXSMMXAAAMASMSMAMMSMAMXSAMSSMMSMSSSMXMMSAMXSASAMAAMXSAMXMXMASAXXSMSMAXAMSSSSSXSSSXSXMXMXSXAXXXM
XSXXAAMSMSAAMSMSXAMAMAAAXMASXMSSSMAAMMSMMXASAXAMAASXMSMSXMAMSSXMMSMXMASAAAAAMAMXAASXSSMAMASXMMSMAAAXMMXXXMASAXAXMMMMMMAXAMAXAMMXAMXSXXMSMMMS
AXMMMMMAAMMSMMAMMSSSSMMMMXAMXXMAXAMXMAAAAXAMXXMSMMMASXXMAMXMAMXMAXXXSMMMSMMSMSXMXXSAMXXAMAMAXMAMSSMMASMSMSMSAMXMASASASAMMMMMAMAMAMXAAMAMASAS
AMAAMASMSMAMMMAMXMAXAXXXAMSSMMMMXSXMMSSSMMMSMMXAMASMMXSSMMAMMSXMASMXMAAXXAXXAXMSXXMASMSXSASMMXMXMAMSXXAAXXASXAXSXMASAXXXXAAXSMSAXXXXMMASXMAS
XSSMSASXAMASASAMAMXMSMMMMSXAXMAMMMSAAMAXXAAAAXSASXSXMAMAASXXXSXSXXAASMMMMSXMAMAAXMMMAMSXSMAMAASMSAMSMMMMSXAMMSMMAMMMMMMMMSMSAAMMSMSMXMXXXMAM
XMXAMASMMMMSASMSAXAAASXAXMMMMSSMSAAMXMASXMSXXMMMMAMMMMXSMMXSASMSAXSAMXAXAMMAAMMMXSASAXMAXMAMSASASXMXMSAAAMMMXAASAMSAXXAAAMMAMXMAAAXAXMMMXAXM
XSAMMMMMXSMMMMASASXSMAXSMMAXMXMAMXSSSMASXMXMSSSXMAMXAMXASAXMAMAXAMXSSXMMASXSXSMXSAASASXSSSSMMAMAMMSAASMSXMASXMXSMSMAMSSMSXSXXAMSMXSXMXAMMMSM
MAMXASAMXAAAMMMMAMXAXMAMASASAAMXMAXAAMXMASXAAAMASXXSAMMAMMSMAMXMSMXXMXMSXMAMAMXXAMXMXMMAAAMAXXMXMXSMMMXAAXASASAXXXXAMXMAXXAAMAMAMXMASXMSAAAX
MASXXSASXSMMSASMMMSXMXXSAMASXXMAMXMXMMMSMMMMMSMMXAMMMSMXMAMMMSMMXAMXMMXAMMMMAMSXMXSXAXMMMMMXMMSMSAXMAAMSSMASMMMXMMSASXSASXMSSSSSSXSAMAASMSMS
SAMXXSAMAXAASXSAMASAMXMMAMXMAXMAMMSMAMAAASMMAAMXXMXAAXMSMMMAXSXAMAMAMXAMSAXXAMXAMASXMMAAMASXMXAAMXSSSSMAAMMMMAMXSASMMXMASAXAAXXAAAMXMMMXAMMS
MMSMXMMMAMMMMMSXMASMSAMXSMMSAXMAMAAXMAXXXXAMSSSMSASMSSXMAASXMSMASAXXSXMMSXXSMMSAMASAXASMSASMSAMXMXXXMAMMSMAASXSAMXSAXSMASXMMSMMMMMMMXSMMXMAX
MMAAAXAMAXXXAXXXMXSXSAXXAMXMAXSAMXMAXAMXSSMMAAAAAMXAAXAXMASAAXAAMXSSMMXMMSMAAXMMMSSMMXMXMASAMASAMMMMSSMMAMMXMMMAXMSAMXMASAXAAAMXAXSMAMAMMMXM
SSSSMSMMSMMMMMMMMXMASAMSSMXMAMMXXMASMASAAAXMASMMXXMMMSSMSAMMMMSASMMAAAXAAAXXMMAXMXMAMSSSMMMXMASASXXAAAASMMSAAXSAMXMSSXMXSAMSMSSXMSMMASAMXXXX
AXAAAXAAXASXSMSASAMXMAMAAMAMXSXMSMAMMAMMSMSAMXMSXMMSMAMAMASXMAMAAAMSXMSMSSMSASXMAASAMAXAXAAXMASAMMMMMSAMAASMSMMXSAAXMASMXXMAMMAMMAMSAMASAMMM
MMSMMMMMSAMASASXSSSXSSMMMSAMAXAMAMAMMASXMMMMXAXMAMAAMAXMMXMXMASMSSMXAMMMAAASAMMMSMSXSMSMMMXSMXMAMXAAAMAMMMSXMXXASMSMSMMXMMSMSMAMSAMMMSMMAXMA
XAMXXAAAMAMXMAMMMAMXMAAXASAXSSSSMSASXMSAAXAXXMSSMMSSSSSMASMMMAXXAAXSXMAMMSMMSMXAAXXMSXSMAXMMMSMMSSMSSSSMMXSAMXMMSAXAAXMAAXAXXXAMMXMMAAXSASAM
MSSSMSMSSXMAMXMAMAMAMMMMMSAXMAAAAXXXAASXMMMSMAAAAAAMMAAXMSAAXASMSMMSMXXSAMMAMXMSSMSXSAMXXXAAAAAAXAAAXMAAAAMAMMASMAMXMSSMSSMSMMSSXSMMSSXMASMS
AXAMAAAMXASXSASMMASMMSASMMMMMAMMMXSXMMMXSAAAMMMSMMSSMSMMXSXMSXSAMXSXSXXMASAXXMAMAASMMSMSSMSSSSMMSMMMSSSMMXSAMAMMMAMASXXXAAMAAXAMXMAAAXXMAMXA
MMAMSMSMAMMMXASXSMSAASXSAASAMXMAXSMSMXMASMSSXSAMXMAMAAXMXMAXSXMAMMMAMMMMMMMXMXSMMMMAAAMAAMAMAXMXAAXSMMAAXXSMXSAMSSSXSASMSMSSSMASXSMMSMMMAXSX
XMAMXXXMAMAXMXMAAXMMMMASMMMMXMXXSMAAXAXAXAAAMMMMSAMXSMSXASMMSMSAMAMXMASAXXMAMAMAXXSMMSSSMMMXSAMSAMXSASXMMXMMAXAAAMMMMXMAXAXAAMSMMXSAAXAMXXSM
MSMSSMMSASXXXAMXMMMAAMAMASMSMSMMMMXMSMSSMMMMMAAXXSAMXAMXXXXXXXXASMSMSXSMSMSASMSMMMSAMXAXMAMXMAMAXXASAMMMSAMMMSAMXSASMAMSMSSSMSXSXMASMSXSSMSA
MAMXAAASASXASMXXXASXMMASXMAAAAMSASAXAAAXAMXMSMMMXMXXAAXSXSSXMAMXMASASASAAASAXAAMAAXAMMXXSASXSXMMSMMMSMAASASAAAASAMMASASAAXAXMXAMMSMMMXMAMAXS
MASXSMMSXXMASAASXMSAMSAMAMSMXMMSASMSMMMXSAMXSAXSAMSSSMAXSAMXMASAMXMAMAMXMXMAMSSSMSSMMSAASASAMSAMXMMAMSMXXAMMXSAMAXMMSXSMSMSMXMAXAAAMAMXMMMMM
SMSMXXMXMXXMMMMMAAMAMMASMMMXSXAMAMXAMAAMMMAXMAXXAMAAAMAMMXMXMASMSMMSMXMAMAMXMAAAMAAMAMXMMAMAMXSAMXMAMMMSXAXXAXMSSMSXXAMMMAMXXXMXSXXMAXXXAXAS
AXMMMASAMSAMXMASMMMSMSMMMAMMAMMXMAXXSMXSAMSXMSMSMMMSMMAXMASMMAMMAXMMASMMSAMSSMXMMMMMSSMXMXMXMAXXSASASAAMXMXMASAAAMXASXSASXSMSAAXAASXMMMSMSAS
MAMAXMMASXASMMMXSXAAMAAAMSXMMAMAXAXXAMMSMSMXXAAAXAMAASXMSASMMSMSASMSAMAAXAMAXAASAMSAMXAAXMMAMXSXSASASMXSASXSAMMMSAMXMAAXSAAASXSXMXMAAXXAAMMM
XASMSAMXMXXMAAMAMMSSMSSMXMAAXXSASMSMASAXMAMAMMSMSMXSXMMMMASAAAXMASASAMXMSXMXSMMXAAMXMASMSASAMMXAMXMAXMASASAMXSMSAASMMXMSMMMMMMMAXASMMMMMSMMS
SMSASXSMMMSSSMMAXXAAAXXXAXAMXXMXSAAMAMMMMAXMAXAMXMAXMMAAMXXMASMMMMMMAMXXAASMSASMSMSAMMXXAMXMSSSMMAMXMMAMXMXMAMXMAMMASAXAXAMSAAXMMMSAXMAMXMAS
AAMAMMXMAAAXAASXXMMXMMAMMSSMMAMAMMMMMAAAMASXMXAMXMASASMSXMASMXXSXAASAMMSMMSASAMAMXSASASMSMXSAMAASMSAXMAMSXMMSSMSSSSXMASXXSSSMSXSAAMMMSSSXSAS
MAMMMMASXSMSSMMSSSMMSMXMAAAAXXMAMAXMSSSXSASMMSSMMMXSAMAMMMXMSMMMSXMMAXAMXXMXMSMXMASAMAMAAASMASXMMASMMSSMMAAAMAAAAXAMXXMMAXAMXMASMSXXXSAMAMXS
XASMAMASXMXXMAMAXAAAMASMMSSMMMSMSMSMAAAAMXMAXAMAMSMMMMMMAMMAAXAMXMSSSMASXXSAXASAMXXMMAMXMSXSMMMAMAMMXMMASMMXSMMMSMMAMMAMXMAMAMMMAMAMXMAMSMAS
MAMXAMXXAMAXXAMMSSMMSAMAAAAAXAAMAASMMSMSMMMMMXSAMAAAXAXXAMMSMSSSSXAAMXMXMASMSMSXSMSMSMSXMXMXMASAMXSXAASAMAXAMASXMAXXAMXMASXSASAMMMMMASAMXMAM
MSMXMSMXXMASXMSXAXMXMMSXMSXMMSMSMAMAXMXXAASASASASMSXSAMMAXMXAXAAXMMSMASAMXMAAXXMMAAXAAMMMAAAMXMAAAMMSMMMSAMXSAMASMMMSSMSXSASASXSXMSSXSAMXMAS
AAAXSAMXAMAXAAXMXMAMSASXMMASMMAMXMXSMXMMSMSASXSAMXMMSASXSMXMMMMMMMAAMASXSAMSMXSAMSMSSSMASASXSASXMMSAMMSMSMMMMAMMMAAAAAAMAMMMXMAXAXMAMXAMMMMA
SMSMSAMMMMSMMMMMXSMAMASXMSASAMXMASAMXAXXXAMAMAMMMMMAMAMAMXMAMASAAMAMXXMAXAXXAASMMXAAAAXMMAMXXAMAMAMXSAAAMAXSSSMSSSMMSMMMMSXMAAAXMMMMAXAMXAAM
XAAMMMMXSAMAXSXSAMAMMAMAXMASAMASAMXSSMMMMMMAMAMMAMXSMMMAMASMMAXMMMSSMSAXSXMMMMSMSMMMMMMSMXMMXMSSMMSASXMSMMMXAMAXAXMAMXAAAXASMMMXMAAXSASMSMSX
MMMMASMXMASMMMAMMSSXMASMMMMMMMXMASAMXMASASMMSMMSASMXASXSSXSAMSSMSAMAAMAXSAXXSXSAXASXMSASMASAMMAXXXMMXAMXAXMMSMMMAMMSXMMMSMMMMAAAMSMMXAXAXAAA
SAAMMSAAMAMXAMXMXXMASXXAXMAAAMMSMMMSAMMSASXMSAASASXSXMAAMXSAMXAXMAMMMMMMXAMAXAMAMXSMASAMSMSAXMAMSAMXMSMSMMSMMASMXMAAAMSMXMAASMSMXAMXMAMMMMMS
SSMSXXMXMXSSXMXXMAMXMSSMSSSSMSAAAXAMAXAMAMAMMMMSAMAMXMSMSASAMMMMSMMASAXXXAMMMXMXMXXMAMXMAMMMMXSSXXXSXMAXMASASAMMAMMSSMAASAMXSXAMSMMAMAMMAMAM
MXMSASXXXMXMAMXMMSAMXASXAAXAXMMMMMMSMMSSMSXMASXMMMAMAXAAMASAMXMAAASASAAMSXMAMMMSMXXMXSXSMSMAAXXMMXMXAMAMXXSXMAXSASXAXXMMMMXAMXMMXSSXSSSSSSSS
AAXMASXMXAAMXSSMAXAAMASXMSMSMSSSMAXAMXXAXSAMASMMMSMSSXMXMXMAMXXSSMMXSMMXAAMMMSAAXXMMXMMSAAXASXSAAMAMXMSMXASXSSMSXSMMXXMMAXMSSSMAAMXAMAAXAAAM
SSMMAMAMASMSAAAMAXMSAMMMXAAAAAAAAXSASMSMMSAMAXAAAAAMAMSXSXSXSMXXXMMMXAAXMMMSAMSSMSAMSAAMSMMMXAXXMASXMAXXXXMASXAXMXMAASMSXSXAAAMMSMXXMMMMMMMM
XXASMSAMMMAMMMMMSMMAMAASMMSMMMSMMMMMXAAXASMMSMXMSSSMMMSAMAAAAXXSSMASXMMMXSXMAMXMAMAMMMMXAXXSMXMMMAMAMAMSXMMMMMSMMAMAMMAAAMMMAMXMAMSXMAMAAXXX
MSMMAMMMAMSMSXSAAAMASXMSXAAAXAAMXAXAMSMMASAAMXMXAMAAXAMAMXMSMAMMASAMAAAAASXMXMAXSSSMMAMMXMSMAMSSMXSXMASMXMAMAAXASXSSSMSMSMSXAMAMAMSAMAMSMSAM
AAMMSMASMSMAXAMMXMMXSXASMSMSMSSSSXSXXAAMAXMMSAMMASXMMMSAMXXAXMXSAMMSSMMMMSAASMSMAAAXMAMSAMAMMMAAXAXASXSAMMSMMMSAMAAAAAXAMASXASASXMSXMAXXAMAS
SASAAMXMXAMSMMMSSMSMSMXSAXAMXXMAXASAMXXMMXSAMAMSMMAXAXSMMMMASXMMAMXAAXXMASMMXAMAMSMXSAMSASASAMSSMXSMMMSASAXASAMAMAMSMMMAMAMMAXXMAXMMSSSMASAM
XXMXSXXXSMMXASAXMAAAXAMMAMXAAMMSMMMSAMXXSAMASMMXASXMSMMMAAMAMXMMMXMASASMAXAMMMMXMAXXMMMSAMXMMXMXMASXAASAMAXAMMSSMXAXAMXAMASXMMASXMAAXAAXXMXX
XSSMMASMXMAMMMMSMSMSMAAMAMXMAMAXASAAMSAMMASAMXXSAMXMAMASMSMSXXAASAMMAMXMAMAMSXSXXXSMXMAMMXSXMAMAMXMXMXMXMXMSMMAMMSSSMMSXSAMAASAMASXSMSMMMMMS
XXAAMAMAMSSMXAXMAXAMXXSXMMMSAMASAMSXXMAXSAMXXMAXMAXSASMSAMXAAXSMSASXAAXASXSASAXMSMMMSSSXSAMASXMXSAMXSAMXSAMAAMASAAXAMXSAMASXMMASAMXMAAAAAXAA
XSMMMAMMMAAMSSSMMMMMAAMASAASXSAMXMXXMSMMMXSAASXXSMASASAMXMMMXMMASAMXXMXMMMMAMAMAAAXAAAXAMASMMSAMSASASAMXSASXSMAMMSXXMAMXMAMAASAMXSAMXSSMMMSS
AAAXSMSMMMXMXAAMSAMXSMSAMMXMAMAMXXXMMAAMXAMXMMAASAMMAMXMXMASXMMAMAMXSMMMAXMXMSASMXMMMMMXMAXXAMMASXMASXMXSXMXAMASXMMMMSSMSAMMMMXSASMSAXAXXXAX
SSMMXAAXMASXXSMMSASAMXMAMSAMXMAMXMSAMAMMMXMXSMMMMAMXXXAMXSASAAMXMXMAAAAMSXSAAXMXMXSMMMSAMXXMSMMMMXMXMMSAMXMXMSXSAMASAAAMSSMSSSXMMSXMXMAMMAMX
XAMXMSMSMMXMAXAXSXMAMASAMXMXAAASAAASMSSSXSSXMASASXMAMSASAMASXMMSSMMSSSMMXASMSMAMXAAAAXSASMMMMASXMAXAAXAXXAMAMMMSMMMMMSMMXAXAAXAAXSXSSMAMXSXM
XSMSAAMAXMAMXMMMSXMAMAMXXAXMASASMSMXXMAMAASASASMSAMXMAMAAMAMAXAXAXAXMAXAMAMMMAASMSSSMXMMAAXAXAMASAMSSMMMMXMASAAMASXAMMXSMMMMSMMSMMAAXMXMAMAM
SMASMXSAXMASAMMXMASAMSSSSXSAMXAXAAAXAAAMMMSXMASMSMMMMASXMMSSSMSSMMSMSSMMSASXMSASAMAMXXSSMXMMSXSAMXMMAMAAXMSASXMMAMXXXAMMAAAAAAAAAMMMXMAMASAM
AMAMMMMMXSASAMAASMMMSXAAXMAXMSMMAMMXMMXSMAXAMXMAXXAAAAXASXAAMAXAXAAMMMMXSASAMXMMXMASMXMASXAMAXSMSMXSASMXSAAXMMXMXSMSMMAMSMMSSXMMXXMSASASMSXS
MMASAXAAMMXMXXSMMAAXXMMMMSMAMAAASXSXXSMMMMSSMSMMSSXSMMSAMXMMSSSSMSXSAAXAMXMMMAAXXMAMMMMAAMSMXXMASAMSAMASMXMASXMSXAAXAMSAMAXMAMSXSMMSASASASMS
XSASMSMSSMMMSXMASXMXXXAAMAXMSSMMMAXMAMAASMAMMXAXXAMMAMMASXXXAXMAXAMSXMXAMXMXSXSMSMMMXXMXMSAMXXMAMAXMAMXASAXMXMAMMMMMXMAASAMMAMMAASAMXMXMAMAM
XMAXAMAMAMAAAAMAMMAMSSSMSAMMAMAAMMMSSSMMXMAMSSXMMMASAXXAMAXMASMMMSMSAMMAMSAMXXMAAAAAMXSMMSASMMMSSMMSMMXMSMSMSMMSASMSSMMMMXXXXMMMMMMXAAXSAMMM
SMSMSMAXMSMSSMMMSMAMXAMXMMMMASXMMSAAAMXSMMSSMMMMAMMSMSMASXMASAAMXMAMAMXSAXSAMXSSSMMSAMXAAXAMXAMMAMMASAMXSXAAAAMSMSAAAMXSASMSXMXSASXSXSASMSXX
XAAAXXMMXXAAAAAAAXAMXAMXMMAMAMASMMMSSMXXAMMAAXAXASASAAXXMMMSMXXMAMAMXSMAAXAXSAMAXAAXMXSMMSMXSSSMAMMASXSAMSSSMSMMXMMMXSAMMSAAAMASXSAAAMXMAMMM
MSMSMASMSMMMSSMSXSSSSXMSMSASASAMXAAAAXMAMSSSMSSSMSMMSMSXMASASASXMSXSAMXMMMMMMASAMMXMSMAMAAMXXMAMXSMMMMMAXAXAAXXMASAAAMASXXMSSMASAMXMXMSMSXAA
AXSXXMAAMXSXXMAXASAMXAAXASASXSAXXMMSSSXSXMAMAAAAASXXAMAMSMSASMAAAXAMXXXMAXAAXAMXXXMMXSASMXSASMSMAMXMASXMMXSMXMASASMSSSSMMAMAXMXMAMAXAXAAXXSM
XSAMXXMXMAAAMAAMXMASXXMMMMAMASXMSMAAAAAMMMAMXMXMMMXSAMXMAMMAMXSMMMXMSAMSASXMSAMAMSMMASXSAAXXAAAMASMSMSAAXMXXASMMAMXXAMXASXMASMSAMXMSXSAMXXMM
MMMMMXXAMSSXAMXMSSSMMAAXXMXMAMXMAMMSSMXMASMSXXXSXSXSXMAXAXMXMAMMXSXAMMAAXMAMMXMAMAAMAMXMMMMSMXMXAMXAASMMMMMSASXSMSMMSASMMSMAXAMAMMMAXSAMSAMX
SASASXMMXAXXMXSSMXMAXSAMXMXMAMMSAMXXXXXSAMAAAMXMASAXAXSSSXSAMXSXAMMMMXSXXMXMMSSSSXSMSSXXAAAXAASMSMSMXMMMXAAMXMAXAAAAAMXAASMMSSMMMAMMXSAMMAMM
SASASMSSSMMSMMMAMMSAMAMSAMXSASAAASMMAXAMMSXMASAMAMMSSMMAAAMASAXMASAMSAMMSMMAAXAAAAXAMXMMSSSMXMSAAAXMXAAMSSXSSXAMSMMMSSSMMMMAAMASASMMAMSMXAMX
MAMMMAAAAXAAAASAMAMSSXMAXXMSASXMSAASAMXMASAXXAAMXSAAAAMMMMSAMXSAXSASMAMSAASMMSMMMMMAMXAAXAAAXXMMMSMSSMMMAMXXAMMXAAMAAXAXMAMMMSAMAXAMXSAMSXSX
MXMSMSMSMMSSSMSASAMXMASMXSXMAMXXMXXMXXMAMSAMXSMMMMMSSXMXXMAMXXSAMMMMMXMMSXMAMSXXMMSSMXSSMSMMXXSSXXAXAMXMASXMASXSSSMMSSSMSASAXMASXSSMMSXMSAMX";
    }

    private static string GetDemoInput()
    {
        return @"MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX";
    }
}